services:
  front:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - back
    restart: unless-stopped
  
  back:
    build: ./back
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./back:/app
      
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo_Db:/data/db
    restart: unless-stopped   

volumes:
  mongo_Db: